### ISSUE TITLE
Chart is indexed even when piechart.Labels.Show is set to false

### ISSUE THREAD

**Issue by Noofbiz** [benoitmasson/plotters#1]
Hello,

When I use 
piechart.Labels.Show = false

My chart still has the index number visible on the resulting pie chart.

**Comment by Noofbiz** [comment]
I actually forked it and fixed the problem. I'm sending a pull request.

**Comment by benoitmasson** [comment]
I did it at the same time ;-) `master` should be fixed now, thanks for reporting and patching

**Comment by Noofbiz** [comment]
No problem, and thank you for being so quick on that lol
